apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-consumer-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: order-consumer
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 10  # Reduced polling interval to 10 seconds for faster scaling
  cooldownPeriod: 10  # Reduced cooldown period to 10 seconds for quicker scale down
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.default.svc.cluster.local:9090
      metricName: rabbitmq_queue_messages
      query: sum(rabbitmq_queue_messages{queue="order-queue"})
      threshold: '3'  # Scale up when there are more than 1 messages in the queue