apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30082 # Access pgAdmin at: http://localhost:30082
  selector:
    app: mongo-express
