apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-handler
  template:
    metadata:
      labels:
        app: user-handler
    spec:
      containers:
      - name: user-handler
        image: jeffreyoechsner/user_handler:latest
        ports:
        - containerPort: 3006
        envFrom:
        - configMapRef:
            name: shopforyou-config
      restartPolicy: Always
