apiVersion: batch/v1
kind: Job
metadata:
  name: sfy-seeder
spec:
  template:
    metadata:
      labels:
        app: sfy-seeder
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z sfu-postgres 5432; do echo waiting for postgres; sleep 2; done;']
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -z sfu-rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
      - name: seeder
        image: jeffreyoechsner/sfy-seeder:latest
        env:
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: password
        - name: RABBIT_USERNAME
          value: root
        - name: RABBIT_PASSWORD
          value: password
        - name: RABBIT_HOST
          value: sfu-rabbitmq
        - name: RABBIT_PORT
          value: "5672"
        - name: DATABASE_URL
          value: postgres://root:password@sfu-postgres:5432/postgres
      restartPolicy: Never
  backoffLimit: 0
