apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfu-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfu-mongodb
  template:
    metadata:
      labels:
        app: sfu-mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: shopforyou-config
        volumeMounts:
        - name: mongodata
          mountPath: /data/db
      volumes:
      - name: mongodata
        persistentVolumeClaim:
          claimName: mongodata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sfu-mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: sfu-mongodb
