server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

# Integration with Grafana Loki:
clients:
  - url: http://loki:3100/loki/api/v1/push # URL of Loki server

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - promtail:9080
        labels:
          job: varlogs
          __path__: /var/log/*.log
          
  - job_name: grocery_handler
    static_configs:
      - targets:
          - promtail:9080
        labels:
          job: grocery_handler
          __path__: /var/log/grocery_handler/*.log

  - job_name: order_handler
    static_configs:
      - targets:
          - promtail:9080
        labels:
          job: order_handler
          __path__: /var/log/order_handler/*.log

  - job_name: order-consumer
    static_configs:
      - targets:
          - promtail:9080
        labels:
          job: order-consumer
          __path__: /var/log/order-consumer/*.log

  - job_name: transaction-processing
    static_configs:
      - targets:
          - promtail:9080
        labels:
          job: transaction-processing
          __path__: /var/log/transaction-processing/*.log