apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-exporter
  template:
    metadata:
      labels:
        app: rabbitmq-exporter
    spec:
      containers:
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter
        ports:
        - containerPort: 9419
        env:
        - name: RABBIT_URL
          value: "http://root:password@sfu-rabbitmq:15672" # Correct URL format
        - name: RABBIT_USER
          value: "root"
        - name: RABBIT_PASSWORD
          value: "password"
        - name: RABBITMQ_EXPORTER_INCLUDE_QUEUES
          value: ".*" # Enable metrics for all queues