apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfu-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfu-rabbitmq
  template:
    metadata:
      labels:
        app: sfu-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            configMapKeyRef:
              name: shopforyou-config
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            configMapKeyRef:
              name: shopforyou-config
              key: RABBITMQ_DEFAULT_PASS
        volumeMounts:
        - name: rabbitmqdata
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmqdata
        persistentVolumeClaim:
          claimName: rabbitmqdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmqdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sfu-rabbitmq
spec:
  type: NodePort
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 31567 # Expose management UI on a fixed NodePort
  selector:
    app: sfu-rabbitmq
