apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfu-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfu-postgres
  template:
    metadata:
      labels:
        app: sfu-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: shopforyou-config
              key: POST_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: shopforyou-config
              key: POST_PASSWORD
        volumeMounts:
        - name: postgresdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgresdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sfu-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: sfu-postgres
