apiVersion: batch/v1
kind: Job
metadata:
  name: sfy-seeder
spec:
  template:
    metadata:
      labels:
        app: sfy-seeder
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z sfu-postgres 5432; do echo waiting for postgres; sleep 2; done;']
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -z sfu-rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
      - name: seeder
        image: jeffreyoechsner/sfy-seeder:latest
        envFrom:
        - configMapRef:
            name: shopforyou-config
      restartPolicy: Never
  backoffLimit: 0
