apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-consumer
  template:
    metadata:
      labels:
        app: order-consumer
    spec:
      containers:
      - name: order-consumer
        image: jeffreyoechsner/order-consumer:latest
        envFrom:
        - configMapRef:
            name: shopforyou-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-consumer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: order-consumer
