apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfu-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfu-mongodb
  template:
    metadata:
      labels:
        app: sfu-mongodb
    spec:
      containers:
        - name: mongo
          image: mongo:latest # Change to your custom image if pushed to a registry
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MON_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MON_PASSWORD
          volumeMounts:
            - name: mongodata
              mountPath: /data/db
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: sfu-mongodb
spec:
  selector:
    app: sfu-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MON_USERNAME: "root"
  MON_PASSWORD: "password"