apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopforyou-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopforyou-client
  template:
    metadata:
      labels:
        app: shopforyou-client
    spec:
      containers:
      - name: shopforyou-client
        image: jeffreyoechsner/shopforyou-client:latest
        ports:
        - containerPort: 8080
        env:
        - name: VITE_GROCERY_HANDLER_URL
          value: "http://localhost:3005"
        - name: VITE_USER_HANDLER_URL
          value: "http://localhost:3006"
        - name: VITE_ORDER_HANDLER_URL
          value: "http://localhost:3007"
        - name: CHOKIDAR_USEPOLLING
          value: "true"
      restartPolicy: Always
