# Use Node.js LTS version
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
COPY ./package*.json ./

# Install dependencies
RUN npm install
RUN npm install -D ts-node typescript @types/node

# Copy the entire order-consumer folder into the container
COPY . .

# Set the default command to run the order-consumer
CMD ["npx", "ts-node", "order-consumer.ts"]