apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-handler
  template:
    metadata:
      labels:
        app: order-handler
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z sfu-postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: order-handler
        image: jeffreyoechsner/order_handler:latest
        ports:
        - containerPort: 3007
        env:
        - name: DATABASE_URL
          value: "postgres://root:password@sfu-postgres:5432/postgres"
        - name: RABBIT_HOST
          value: "sfu-rabbitmq"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USERNAME
          value: "root"
        - name: RABBIT_PASSWORD
          value: "password"
      restartPolicy: Always
