apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfu-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfu-rabbitmq
  template:
    metadata:
      labels:
        app: sfu-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
        - configMapRef:
            name: shopforyou-config
