apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfu-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfu-rabbitmq
  template:
    metadata:
      labels:
        app: sfu-rabbitmq
    spec:
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
        - name: rabbitmq-logs
          hostPath:
            path: /var/log/rabbitmq
            type: DirectoryOrCreate
      initContainers:
        - name: init-rabbitmq-logs
          image: busybox
          command: ["sh", "-c", "mkdir -p /var/log/rabbitmq && touch /var/log/rabbitmq/rabbitmq.log"]
          volumeMounts:
            - name: rabbitmq-logs
              mountPath: /var/log/rabbitmq
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
        - configMapRef:
            name: shopforyou-config
        volumeMounts:
          - name: rabbitmq-config
            mountPath: /etc/rabbitmq/rabbitmq.conf
            subPath: rabbitmq.conf
          - name: rabbitmq-logs
            mountPath: /var/log/rabbitmq
