apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocery-handler
  template:
    metadata:
      labels:
        app: grocery-handler
    spec:
      initContainers:
        - name: init-grocery-handler-logs
          image: busybox
          command: ["sh", "-c", "mkdir -p /var/log/grocery-handler && touch /var/log/grocery-handler/grocery-handler.log"]
          volumeMounts:
            - name: grocery-handler-logs
              mountPath: /var/log/grocery-handler
      containers:
      - name: grocery-handler
        image: jeffreyoechsner/grocery_handler:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        envFrom:
        - configMapRef:
            name: shopforyou-config
        volumeMounts:
        - name: grocery-handler-logs
          mountPath: /var/log/grocery-handler
      restartPolicy: Always
      volumes:
        - name: grocery-handler-logs
          hostPath:
            path: /var/log/grocery-handler
            type: DirectoryOrCreate
