apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocery-handler
  template:
    metadata:
      labels:
        app: grocery-handler
    spec:
      containers:
      - name: grocery-handler
        image: jeffreyoechsner/grocery_handler:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        envFrom:
        - configMapRef:
            name: shopforyou-config
