services:
  sfu-mongodb: 
    build: .
    ports:
      - "27018:27017"
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MON_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MON_PASSWORD}
    #command: ["/bin/bash", "/docker-entrypoint-initdb.d/mongo_init.sh"]
    
    volumes:
      - mongodata:/data/db                                         # persisten mongoDB data volume, to keep data across restarts
volumes:
  mongodata:
    driver: local
networks:
  backend: 