apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: shopforyou-config
              key: MON_HOST
        - name: ME_CONFIG_MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: shopforyou-config
              key: MON_PORT
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            configMapKeyRef:
              name: shopforyou-config
              key: MON_USERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            configMapKeyRef:
              name: shopforyou-config
              key: MON_PASSWORD
        - name: ME_CONFIG_BASICAUTH
          value: "false"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080
  selector:
    app: mongo-express
