apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfu-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfu-pgadmin
  template:
    metadata:
      labels:
        app: sfu-pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: shopforyou-config
        volumeMounts:
        - name: pgadmindata
          mountPath: /var/lib/pgadmin
        - name: pgadmin-servers
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
          readOnly: true
      volumes:
      - name: pgadmindata
        persistentVolumeClaim:
          claimName: pgadmindata
      - name: pgadmin-servers
        configMap:
          name: pgadmin-servers
