apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocery-handler
  template:
    metadata:
      labels:
        app: grocery-handler
    spec:
      containers:
      - name: grocery-handler
        image: jeffreyoechsner/grocery_handler:latest
        ports:
        - containerPort: 3005
        envFrom:
        - configMapRef:
            name: shopforyou-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: grocery-handler
spec:
  type: NodePort
  ports:
    - port: 3005
      targetPort: 3005
      nodePort: 30305
  selector:
    app: grocery-handler
