apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocery-handler
  template:
    metadata:
      labels:
        app: grocery-handler
    spec:
      containers:
      - name: grocery-handler
        image: jeffreyoechsner/grocery_handler:latest
        ports:
        - containerPort: 3005
        envFrom:
        - configMapRef:
            name: shopforyou-config
        volumeMounts:
          - name: grocery-handler-logs
            mountPath: /var/log/grocery-handler
      restartPolicy: Always
      volumes:
        - name: grocery-handler-logs
          hostPath:
            path: /var/log/grocery-handler
---
apiVersion: v1
kind: Service
metadata:
  name: grocery-handler
spec:
  type: NodePort
  ports:
    - port: 3005
      targetPort: 3005
      nodePort: 30005
  selector:
    app: grocery-handler
